-- 1. Table: Roles
CREATE TABLE roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(20) NOT NULL UNIQUE,
    description TEXT,
    
    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- 2. Table: Departments
CREATE TABLE departments (
    department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    office_location VARCHAR(100),

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- 3. Table: Users
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE, 
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL,
    
    -- Account Status & Tracking
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING_VERIFICATION' CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'PENDING_VERIFICATION')),
    email_verified BOOLEAN DEFAULT FALSE,
    email_verified_at TIMESTAMP,
    ban_reason TEXT,
    profile_picture_url VARCHAR(255),
    
    -- Login Tracking
    last_login_at TIMESTAMP,
    last_login_ip VARCHAR(45),
    login_count INT DEFAULT 0,

    -- Foreign Key
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(role_id),

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- 4. Table: Teachers
CREATE TABLE teachers (
    teacher_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT UNIQUE,
    department_id INT,
    
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    specialization VARCHAR(100),

    -- Foreign Keys
    CONSTRAINT fk_teachers_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_teachers_department FOREIGN KEY (department_id) REFERENCES departments(department_id) ON DELETE SET NULL,

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- 5. Table: Students
CREATE TABLE students (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT UNIQUE,
    department_id INT,

    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    dob DATE,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    address VARCHAR(255),

    -- Foreign Keys
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_students_department FOREIGN KEY (department_id) REFERENCES departments(department_id) ON DELETE SET NULL,

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- 6. Table: Courses
CREATE TABLE courses (
    course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    credits INT NOT NULL CHECK (credits > 0),
    description TEXT,

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- 7. Table: Scheduled Classes
CREATE TABLE scheduled_classes (
    class_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INT NOT NULL,
    teacher_id INT,
    
    semester VARCHAR(20) NOT NULL,
    year INT NOT NULL,
    room_number VARCHAR(20),
    schedule VARCHAR(50), -- e.g., "Mon 8:00-10:00"

    -- Foreign Keys
    CONSTRAINT fk_classes_course FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE,
    CONSTRAINT fk_classes_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(teacher_id) ON DELETE SET NULL,

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- 8. Table: Enrollments
CREATE TABLE enrollments (
    enrollment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    class_id INT NOT NULL,
    enrollment_date DATE NOT NULL DEFAULT CURRENT_DATE,

    -- Constraints
    UNIQUE (student_id, class_id),
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
    CONSTRAINT fk_enrollments_class FOREIGN KEY (class_id) REFERENCES scheduled_classes(class_id) ON DELETE CASCADE,

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- 9. Table: Grades
CREATE TABLE grades (
    grade_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INT NOT NULL,
    grade_value DECIMAL(4, 2) CHECK (grade_value >= 0 AND grade_value <= 10.00), -- 0.00 to 10.00 scale
    feedback TEXT,

    -- Foreign Key
    CONSTRAINT fk_grades_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- Indexes for performance (Optional but recommended)
-- CREATE INDEX idx_users_username ON users(username);
-- CREATE INDEX idx_students_email ON students(email);
-- CREATE INDEX idx_teachers_email ON teachers(email);
