-- =============================================
-- V2: Add semesters table + new profile fields
-- =============================================

-- 1. Semesters table (3 kỳ mỗi năm: SPRING, SUMMER, FALL)
CREATE TABLE semesters (
    semester_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL CHECK (name IN ('SPRING', 'SUMMER', 'FALL')),
    year INT NOT NULL,
    start_date DATE,
    end_date DATE,
    is_current BOOLEAN DEFAULT FALSE,

    -- Unique constraint: mỗi năm chỉ có 1 kỳ Spring, 1 Summer, 1 Fall
    UNIQUE (name, year),

    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP
);

-- Chỉ cho phép 1 semester is_current = true
CREATE UNIQUE INDEX idx_semesters_current ON semesters (is_current) WHERE is_current = TRUE;

-- 2. Student: thêm gender, major, student_code, gpa
ALTER TABLE students ADD COLUMN gender VARCHAR(10);
ALTER TABLE students ADD COLUMN major VARCHAR(100);
ALTER TABLE students ADD COLUMN student_code VARCHAR(10) UNIQUE;
ALTER TABLE students ADD COLUMN gpa DECIMAL(3, 2) DEFAULT 0.00 CHECK (gpa >= 0 AND gpa <= 4.00);

CREATE INDEX idx_students_student_code ON students(student_code);

-- 3. Teacher: thêm teacher_code, academic_rank, office_room
ALTER TABLE teachers ADD COLUMN teacher_code VARCHAR(10) UNIQUE;
ALTER TABLE teachers ADD COLUMN academic_rank VARCHAR(50);
ALTER TABLE teachers ADD COLUMN office_room VARCHAR(50);

CREATE INDEX idx_teachers_teacher_code ON teachers(teacher_code);

-- 4. Seed data: semester hiện tại
INSERT INTO semesters (name, year, start_date, end_date, is_current) VALUES
    ('SPRING', 2026, '2026-01-12', '2026-05-10', TRUE),
    ('SUMMER', 2026, '2026-05-18', '2026-08-15', FALSE),
    ('FALL', 2026, '2026-09-01', '2026-12-20', FALSE),
    ('SPRING', 2025, '2025-01-13', '2025-05-11', FALSE),
    ('SUMMER', 2025, '2025-05-19', '2025-08-16', FALSE),
    ('FALL', 2025, '2025-09-01', '2025-12-21', FALSE);
